# Generated by Django 3.2.16 on 2022-11-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_rename_member_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='face_3D_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hair_area',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='hair_mask',
            field=models.ImageField(blank=True, null=True, upload_to='masks/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim1_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim1_url',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim2_url',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim3_url',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
