# Generated by Django 3.2.16 on 2022-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_auto_20221104_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hair_area_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hair_mask_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim1_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim2_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim3_url',
        ),
        migrations.AddField(
            model_name='post',
            name='hair_area',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='hair_mask',
            field=models.ImageField(blank=True, null=True, upload_to='masks/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim1',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim2',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim3',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
    ]
