# Generated by Django 3.2.16 on 2022-11-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_auto_20221104_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hair_area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hair_mask',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ssim3',
        ),
        migrations.AddField(
            model_name='post',
            name='hair_area_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hair_mask_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim1_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim2_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim3_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
