# Generated by Django 3.2.16 on 2022-11-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0006_auto_20221104_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ssim2_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ssim3_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
