# Generated by Django 3.2.16 on 2022-11-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_auto_20221104_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='back_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='back_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='back_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='front_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='front_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='front_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ratio_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ratio_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ratio_z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='side_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='side_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='side_z',
            field=models.FloatField(null=True),
        ),
    ]
